name: Hello Workflow

on: [push]

jobs:
  build:
    name: Hello
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Write a message
        run: |
          echo "Isto é uma mensagem"
